.TH MONITOR 1 "10 June 2012"
.SH NAME
monitor \- A simple lightweight network monitor.
.SH SYNOPSIS
.B monitor
[
.I OPTION
] [
.I INTERFACE
]
.SH DESCRIPTION
.I monitor
A network interface in real-time through a minimal display window.
.SH OPTIONS
.TP
.B \-l, \-\-list
Print a list of available network interfaces.
.TP
.B \-h, \-\-help
Print available command line options.
.SH AUTHOR
Christopher Hoobin <christopher.hoobin@gmail.com>
.LP
